[project]
name = "sbsvf-api"
version = "0.1.2"
description = "gRPC (SIM/AV) API contract for SBSVF"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["grpcio>=1.76.0", "protobuf>=6.33.5"]

[dependency-groups]
dev = ["grpcio-tools>=1.76.0"]
