[project]
name = "carla-api"
version = "0.1.0"
description = "gRPC API contract for CARLA simulator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["grpcio>=1.76.0", "protobuf>=6.33.5"]

[project.optional-dependencies]
dev = ["grpcio-tools"]
